import pytest

from bioage.reference import regenerate_kdm
from bioage.reference.loader import get_kdm


def test_kdm_biomarkers_yaml_matches_fit_of_the_embedded_norms():
    """METHODOLOGY §7 says kdm_biomarkers.yaml must never be hand-edited -- only
    regenerated by running `python -m bioage.reference.regenerate_kdm` against the
    NORMS table embedded in that script. Nothing enforced that guarantee before this
    test: it regenerates every biomarker's (q, k, s) directly from the embedded norms
    and compares against what the application actually loads, so a hand-edit (or a
    NORMS change nobody re-ran the regeneration for) fails loudly instead of silently
    drifting out of sync with the auditable derivation it's supposed to match.
    """
    loaded = get_kdm().biomarkers
    assert set(loaded) == set(regenerate_kdm.NORMS)

    # The YAML rounds each value to 6 decimal places (regenerate_kdm.main); tight
    # enough to catch a hand-edit or a stale value, loose enough not to fail on that
    # rounding alone -- rel alone is too strict for k's small magnitudes (as low as
    # ~0.0386), so abs backstops it.
    for name, spec in regenerate_kdm.NORMS.items():
        q, k, s = regenerate_kdm.fit(spec["points"])
        marker = loaded[name]
        assert marker.q == pytest.approx(q, rel=1e-5, abs=1e-5), f"{name}.q drifted"
        assert marker.k == pytest.approx(k, rel=1e-5, abs=1e-5), f"{name}.k drifted"
        assert marker.s == pytest.approx(s, rel=1e-5, abs=1e-5), f"{name}.s drifted"


def test_kdm_k_signs_match_the_documented_direction_of_each_biomarker():
    """resting_hr_bpm and bmi rise with age (positive k); hrv_rmssd_ms,
    mean_daily_steps, and sleep_efficiency_pct decline with age (negative k) -- per
    docs/METHODOLOGY.md §4.4's table and the age-stratified means in
    regenerate_kdm.NORMS. A sign flip here would silently invert how one of these
    biomarkers pulls the KDM estimate, so it's worth pinning down directly rather than
    only implicitly via the numeric-match test above."""
    biomarkers = get_kdm().biomarkers
    assert biomarkers["resting_hr_bpm"].k > 0
    assert biomarkers["bmi"].k > 0
    assert biomarkers["hrv_rmssd_ms"].k < 0
    assert biomarkers["mean_daily_steps"].k < 0
    assert biomarkers["sleep_efficiency_pct"].k < 0
