"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-02 16:32:35.147131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Declared standalone (create_type=False) so upgrade/downgrade can create and drop it
# explicitly. Postgres does not drop enum types automatically when a table that used
# them is dropped, so without this, `downgrade()` would leave the `sex` type behind
# and a subsequent `upgrade()` would fail with "type sex already exists".
sex_enum = postgresql.ENUM('male', 'female', name='sex', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sex_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('bioage_scores',
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('chronological_age', sa.Float(), nullable=False),
    sa.Column('composite_age', sa.Float(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=False),
    sa.Column('ci_high', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('week_start')
    )
    op.create_table('daily_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('resting_hr_bpm', sa.Float(), nullable=True),
    sa.Column('hrv_rmssd_ms', sa.Float(), nullable=True),
    sa.Column('hrv_average_ms', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_zone_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_total_min', sa.Float(), nullable=True),
    sa.Column('sleep_efficiency_pct', sa.Float(), nullable=True),
    sa.Column('waso_min', sa.Float(), nullable=True),
    sa.Column('deep_pct', sa.Float(), nullable=True),
    sa.Column('rem_pct', sa.Float(), nullable=True),
    sa.Column('sleep_midpoint_local_min', sa.Float(), nullable=True),
    sa.Column('respiratory_rate_brpm', sa.Float(), nullable=True),
    sa.Column('spo2_pct', sa.Float(), nullable=True),
    sa.Column('skin_temp_delta_c', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('measured_on', sa.Date(), nullable=False),
    sa.CheckConstraint("kind IN ('height_m', 'weight_kg', 'waist_cm')", name='ck_measurement_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'measured_on', name='uq_measurement_kind_date')
    )
    op.create_index(op.f('ix_measurements_measured_on'), 'measurements', ['measured_on'], unique=False)
    op.create_table('oauth_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_oauth_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sex_enum, nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_profile_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_data_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('point_date', sa.Date(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_type', 'point_date', name='uq_raw_type_date')
    )
    op.create_index(op.f('ix_raw_data_points_data_type'), 'raw_data_points', ['data_type'], unique=False)
    op.create_index(op.f('ix_raw_data_points_point_date'), 'raw_data_points', ['point_date'], unique=False)
    op.create_table('sync_state',
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('synced_through', sa.Date(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('data_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_raw_data_points_point_date'), table_name='raw_data_points')
    op.drop_index(op.f('ix_raw_data_points_data_type'), table_name='raw_data_points')
    op.drop_table('raw_data_points')
    op.drop_table('profile')
    op.drop_table('oauth_credentials')
    op.drop_index(op.f('ix_measurements_measured_on'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('daily_metrics')
    op.drop_table('bioage_scores')
    # ### end Alembic commands ###
    sex_enum.drop(op.get_bind(), checkfirst=True)
